### ISSUE TITLE
Add 'nettigritty' Domain Registrar

### ISSUE THREAD

**Issue by pajeb4you** [ValEXE-Technologies/Lookup.Services#5]
Add support for 'nettigritty' domain registrar; to start with only INR currency

**Comment by indra4you** [comment]
Integrated 'nettigritty' registrar - [Commit](https://github.com/ValEXE-Technologies/Lookup.Services/commit/13cfd2cea4c0dd7d5df0d91c2fc9eee8c4c221db)
