### ISSUE TITLE
RegEx to extract price is not working for amount with ","

### ISSUE THREAD

**Issue by pajeb4you** [ValEXE-Technologies/Lookup.Services#9]
The `NUMERIC_REGEX` RegEx defined in `BaseDomainRegistrar` to extract price from InnerHtml is not working for the amount/value having `,/comma`.  RegEx need to updated to fix this bug.

**Comment by indra4you** [comment]
Fixed with workaround (removing `,` from innerHtml) instead of updating RegEx - (Commit)[https://github.com/ValEXE-Technologies/Lookup.Services/commit/d9ba3ed4d1a510d0a8379257ca00c593af66a572]
